### ISSUE TITLE
Can't get data from a given Collection using the SDK

### ISSUE THREAD

**Issue by facundofarias** [keenlabs/KeenClient-Java#16]
I know I can write unit tests with some proper mocking framework (such as Mockito), and mock your SDK, and in this way check if the events are being saved on Keen. But, it would be good also to have some API to retrieve data from a given collection, just in case I want to get data, and check if it was written correctly (I mean, some kind of integration tests). 

I know that I can use the REST API to do a query, but I have to build everything *by hand*, it would be nice to have it on the SDK instead. Just an idea.

**Comment by Geeber** [comment]
This has been addressed with the addition of the query client.
