### ISSUE TITLE
KeenCallback with event map parameters

### ISSUE THREAD

**Issue by mikereinhold** [keenlabs/KeenClient-Java#32]
I have a use case for the KeenCallback where I would want to retry sending an event, persist the event for later, or log information that would help determine which event failed to publish.

Unfortunately, the current KeenCallback interface does not allow for Keen to pass the event data (project, collection, event properties, keen properties) to the callback so that further action can be taken (such as retrying, detailed logging, event storage, etc). 

Adding these parameters to the callback methods or creating additional callback methods would constitute a breaking change to the interface as all existing implementations would need to be modified in order to compile with the new version of the interface.

My suggestion would be to create an additional callback interface, perhaps KeenEventCallback or something similar, that extends the KeenCallback interface with these new methods. Developers that need this type of callback could implement the advanced interface and pass it to the KeenClient during event publishing. 

The KeenClient would need to be modified to check if the callback is an advanced callback and, if so, call the appropriate new callback method in place of or in addition to the original callback method.

If you think that other users of the Keen Java SDK would benefit from this feature, I would be happy to discuss further and put together a PR.

**Comment by josephwegner** [comment]
Looks like this was resolved. Closing.
