### ISSUE TITLE
New Crash Group for huedoku 1.1 (5)

### ISSUE THREAD

**Issue by lexicography** [keenlabs/KeenClient-Java#43]
Timeout trying to send data to keen.

http://cl.ly/091g452B1Z0P?_ga=1.182769446.1852350949.1425422880

X-Eon-Dm: dm0208
Return-Path: <0000014be12a234e-ade75f62-a273-496d-95d9-3a71c3be2bbe-000000@amazonses.com>
Received: from a8-38.smtp-out.amazonses.com (a8-38.smtp-out.amazonses.com [54.240.8.38])
	by dm0208.mta.everyone.net (EON-INBOUND) with ESMTP id dm0208.54ed0dd6.dd899c
	for <fractal@maui.net>; Tue, 3 Mar 2015 11:43:32 -0800
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=224i4yxa5dv7c2xz3womw6peuasteono; d=amazonses.com; t=1425411810;
	h=Date:From:To:Message-ID:Subject:Mime-Version:Content-Type:Content-Transfer-Encoding:Feedback-ID;
	bh=C1X+rQFbnqicGW8ZjCXNFWiKwgPnbgKMkgQ/b5lEE24=;
	b=J0PCVgiQ5uyd2v5wQkepF1ZgQGLcgd2RDw+QXCi7nEmUhw1z5t6Gi2Rr1cITyHpu
	1yTZl5XHNFEFWLR8OSGtUXlbaVQAszwu6vBXTzTklcEhsecrjUIOhUX7uPMhbkmh4C7
	7EbLxxTS32TVOZRNIWU62NAVelbBSDn6vfWTQoy8=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=jivsh7bfp4m6jigp3jpzsonmbsz3s7dl; d=hockeyapp.net; t=1425411810;
	h=Date:From:To:Message-ID:Subject:Mime-Version:Content-Type:Content-Transfer-Encoding;
	bh=C1X+rQFbnqicGW8ZjCXNFWiKwgPnbgKMkgQ/b5lEE24=;
	b=Sd44VKggBdc6mgicuo0u3POL1+D9Q9A1D/llHJlhWP4zjAEVC9kWttugb3FJwO02
	TL4e4hQvybs4WyrhpKbeIattnXsyP5TPK34/UDiaT1szr09PfWRmncW05TW7gFfYLa7
	VCN9JnzsZbgM9q6LHt987g7s7s8rjbqNebcTdfTE=
Date: Tue, 3 Mar 2015 19:43:30 +0000
From: HockeyApp <notification@hockeyapp.net>
To: fractal@maui.net
Message-ID: <0000014be12a234e-ade75f62-a273-496d-95d9-3a71c3be2bbe-000000@email.amazonses.com>
Subject: New Crash Group for huedoku 1.1 (5)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_54f60ee2cde1_46fff2e0f4730e3";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-SES-Outgoing: 2015.03.03-54.240.8.38
Feedback-ID: 1.us-east-1.oTMZEeVd2+LMait86PfB2/S1KcIyX4fprYdxw8oBSqU=:AmazonSES
Sender: <0000014be12a234e-ade75f62-a273-496d-95d9-3a71c3be2bbe-000000@amazonses.com>

----==_mimepart_54f60ee2cde1_46fff2e0f4730e3
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

HockeyApp created a new crash group for this app:
huedoku 1.1 (5)

Reason:
java.lang.RuntimeException: java.net.ConnectException: failed to connect to api.keen.io/108.168.254.131 (port 443) after 30000ms: connect failed: ENETUNREACH (Network is unreachable)

Location:
io.keen.client.java.KeenClient.handleFailure, line 1345

View on HockeyApp:
https://rink.hockeyapp.net/manage/apps/103879/crash_reasons/29510737?no_iphone_ui=true

If you have any questions, please contact us at support@hockeyapp.net or support.hockeyapp.net.

----==_mimepart_54f60ee2cde1_46fff2e0f4730e3
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<style>
  html {
    -webkit-text-size-adjust: none;
  }
  
  body, html {
    background-color: #fff; 
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 12px;
    margin: 0px; 
    padding: 0px;
    width: 100%;
  }      
  
  h2 {
    font-size: 120%;
  }
  
  h3 {
    background: #dce0e3;
    border-top: 1px solid #fff;
    margin: 0px;
    padding: 10px 15px;
    font-size: 100%;
  }
  
  ul {
    margin-left: 20px;
    padding-left: 0px;
  }
  
  div.well-container {
    margin: 0px;
    padding: 0px;
  }
  
  div.well {
    padding: 0px;
  }
  
  div.below-well {
    border-top: 1px solid #dce0e3;
    color: #000;
    padding: 10px 0px;
    text-align: center;
  }
  
  div.below-well a {
    color: #3f4e57 !important;
    text-decoration: underline;
  }
  
  div.message-header {
    background: #fff;
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(255, 255, 255, 0.0)), to(rgba(248, 249, 251, 1.0)));
    background-image: -moz-linear-gradient(center top, rgba(255, 255, 255, 0) 0%, rgba(248, 249, 251, 1.0) 100%);
    border-bottom: 1px solid #dce0e3;
    padding: 10px 15px;
  }
  
  div.message-header img {
    border-radius: 4px; 
    -webkit-border-radius: 4px; 
    -moz-border-radius: 4px;
    float: right;
    height: 36px;
    width: 36px;
  }
  
  div.message-body, div.message-help {
    padding: 10px 15px;
  }
  
  div.message-help {
    border-top: 1px solid #dce0e3;
  }
  
  div.message-help li {
    margin-bottom: 15px;
  }
  
  div.small_icon, div.small_icon_no_border {
    display: block;
    float: none;
    margin: 4px 0px 0px 0px;
    padding: 0px;
    text-align: center;
    width: 36px;
  }
  
  div.small_icon span.highlight {
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(255, 255, 255, 0.699219)), to(rgba(255, 255, 255, 0.199219)));
    background-image: -moz-linear-gradient(center top, rgba(255, 255, 255, 0.699219) 0%, rgba(255, 255, 255, 0.199219) 100%);
    border-bottom-left-radius: 20px 6px;
    border-bottom-right-radius: 25px 6px;
    border-top-left-radius: 9px 9px;
    border-top-right-radius: 9px 9px;
    display: block;
    height: 18px;
    margin: -1px 0px;
    position: absolute;
    width: 36px;
    z-index: 5;
  }
  
  div.small_icon img, div.small_icon_no_border img {
    color: #888;
    width: 36px;
    height: 36px;
  }
  
  div.small_icon img {
    -webkit-box-shadow: 0px 2px 4px rgba(0,0,0,0.5);
    -moz-box-shadow: 0px 2px 4px rgba(0,0,0,0.5);
    box-shadow: 0px 2px 4px rgba(0,0,0,0.5);
    border-radius: 6px;
  }
  
  .btn {
    background-color: #f5f5f5;
    background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6);
    background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6);
    background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6));
    background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6);
    background-image: -o-linear-gradient(top, #ffffff, #e6e6e6);
    background-image: linear-gradient(top, #ffffff, #e6e6e6);
    background-repeat: repeat-x;
    border: 1px solid #cccccc;
    border-bottom-color: #b3b3b3;
    border-color: #e6e6e6 #e6e6e6 #bfbfbf;
    border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
    border-radius: 4px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
    -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
    -moz-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
    color: #fff;
    color: #333333;
    cursor: pointer;
    display: inline-block;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#e6e6e6', GradientType=0);
    filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
    font-size: 13px;
    padding: 4px 10px 4px;
    line-height: 18px;
    margin-bottom: 0;
    text-align: center;
    text-decoration: none;
    text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);        
    vertical-align: middle;
  }
  
  .btn-ha-primary {
    color: #ffffff;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
    background-color: #389be8;
    background-image: -moz-linear-gradient(top, #4aa4ea, #1c8de5);
    background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#4aa4ea), to(#1c8de5));
    background-image: -webkit-linear-gradient(top, #4aa4ea, #1c8de5);
    background-image: -o-linear-gradient(top, #4aa4ea, #1c8de5);
    background-image: linear-gradient(to bottom, #4aa4ea, #1c8de5);
    background-repeat: repeat-x;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff4aa4ea', endColorstr='#ff1c8de5', GradientType=0);
    border-color: #1c8de5 #1c8de5 #1363a2;
    border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
    *background-color: #1c8de5;
    filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
  }
  
  .btn-ha-primary:hover,
  .btn-ha-primary:focus,
  .btn-ha-primary:active,
  .btn-ha-primary.active,
  .btn-ha-primary.disabled,
  .btn-ha-primary[disabled] {
    color: #ffffff;
    background-color: #1c8de5;
    *background-color: #187fcf;
  }
  
  .btn-ha-primary:active,
  .btn-ha-primary.active {
    background-color: #1571b9 ;
  }
  
  div.message-help li .btn {
    margin-top: 5px;
  }
  
  div.overflow {
    overflow: scroll;
    max-width: 100%;
  }
  
  @media only screen and (min-device-width:768px) {
    body, html {
      background-color: #f3f6f8; 
    }
  
    div.well-container {
      margin: 0px;
      padding: 20px;
    }
  
    div.well {
      background-color: #fff; 
      border-radius: 4px; 
      -webkit-border-radius: 4px; 
      -moz-border-radius: 4px;
      box-shadow: 0 2px 2px rgba(0, 0, 0, 0.5); 
      -moz-box-shadow: 0 2px 2px rgba(0, 0, 0, 0.5); 
      -webkit-box-shadow: 0 2px 2px rgba(0, 0, 0, 0.5); 
    }
  
    div.below-well {
      border-top: none;
      padding: 20px 10px 10px;
      text-align: right;
    }
  }
  
  .progress {
    overflow: hidden;
    height: 18px;
    margin-bottom: 0px;
    background-color: #f7f7f7;
    background-image: -moz-linear-gradient(top, #f5f5f5, #f9f9f9);
    background-image: -ms-linear-gradient(top, #f5f5f5, #f9f9f9);
    background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#f5f5f5), to(#f9f9f9));
    background-image: -webkit-linear-gradient(top, #f5f5f5, #f9f9f9);
    background-image: -o-linear-gradient(top, #f5f5f5, #f9f9f9);
    background-image: linear-gradient(top, #f5f5f5, #f9f9f9);
    background-repeat: repeat-x;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f5f5f5', endColorstr='#f9f9f9', GradientType=0);
    -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
    -moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
  }
  .progress .bar {
    width: 0%;
    height: 18px;
    line-height: 18px;
    color: #ffffff;
    font-size: 12px;
    text-align: left;
    padding: 0px 5px;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
    background-color: #0e90d2;
    background-image: -moz-linear-gradient(top, #149bdf, #0480be);
    background-image: -ms-linear-gradient(top, #149bdf, #0480be);
    background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#149bdf), to(#0480be));
    background-image: -webkit-linear-gradient(top, #149bdf, #0480be);
    background-image: -o-linear-gradient(top, #149bdf, #0480be);
    background-image: linear-gradient(top, #149bdf, #0480be);
    background-repeat: repeat-x;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#149bdf', endColorstr='#0480be', GradientType=0);
    -webkit-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
    -moz-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
    box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    box-sizing: border-box;
    -webkit-transition: width 0.6s ease;
    -moz-transition: width 0.6s ease;
    -ms-transition: width 0.6s ease;
    -o-transition: width 0.6s ease;
    transition: width 0.6s ease;
  
    float: left;
  }
  
  .sec-label {
    height: 18px;
    line-height: 18px;
    float: left;
    margin-left: 5px;
    font-size: 12px;
    color: #0088cc;
  }
  
  table a {
    text-decoration: none;
    color: #0088cc;
  }
  
  table a:hover {
    text-decoration: none;
    color: #005580;
  }
  
  td.app-title {
    white-space: nowrap;
  }
  
  table.table-bordered {
    border-left: none;
    border-right: none;
    border-top: none;
    border-bottom: none;
    border-radius: 0px; }
    table.table-bordered th, table.table-bordered td {
      border-left: none;
      border-right: none;
      border-radius: 0px !important; }
    table.table-bordered th {
      border-color: transparent;
      border-width: 0px 0px 0px 1px;
      -webkit-border-image: -webkit-gradient(linear, 0 100%, 0 20%, from(#dedede), to(rgba(222, 222, 222, 0))) 1 100%; }
    table.table-bordered th:first-of-type, table.table-bordered th.actions {
      border-left: none;
      border-width: 0px; }
    table.table-bordered th.icon + th.title {
      border: none; }
    table.table-bordered col.new-actions {
      width: 30px; }
    table.table-bordered th.new-actions, table.table-bordered td.new-actions {
      text-align: center; }
      table.table-bordered th.new-actions .btn-group, table.table-bordered td.new-actions .btn-group {
        float: none; }
      table.table-bordered th.new-actions .btn-group > .dropdown-toggle, table.table-bordered td.new-actions .btn-group > .dropdown-toggle {
        box-shadow: none;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        opacity: 0.2;
        padding: 0px; }
      table.table-bordered th.new-actions .btn-group > .dropdown-toggle:hover, table.table-bordered td.new-actions .btn-group > .dropdown-toggle:hover {
        opacity: 1.0; }
      table.table-bordered th.new-actions ul, table.table-bordered td.new-actions ul {
        min-width: 80px !important; }
        table.table-bordered th.new-actions ul li, table.table-bordered td.new-actions ul li {
          text-align: left; }
  
      table tr > td:first-child { padding-right:10px }
  
  div.below-headline table {
    border-top: 1px solid #eee; }
  
  div#infinite {
    padding-bottom: 20px; }
</style>
</head>
<body>
<div class='well-container'>
<div class='well'>
<div class='message-header'>
<table cellpadding='0' cellspacing='0' width='100%'>
<tr valign='top'>
<td width='100%'>
<h2>
huedoku 1.1 (5)
</h2>
<p>
<strong>Platform:</strong>
Android
<br>
<strong>Release Type:</strong>
Beta
</p>
</td>
<td height='36px' width='72px'>
<div class='small_icon_no_border'>
<img alt="Db495b655fd2bbf4c2ed1e0ce4f821e7" src="https://dl0tgz6ee3upo.cloudfront.net/production/apps/icons/000/103/879/email/db495b655fd2bbf4c2ed1e0ce4f821e7.png" style="color: #888;
 width: 36px;
 height: 36px;" />
</div>
</td>
</tr>
</table>
</div>
<div class='message-body'>
<p>
HockeyApp created a new crash group.
</p>
<p>
<strong>Reason:</strong>
<br>
java.lang.RuntimeException: java.net.ConnectException: failed to connect to api.keen.io/108.168.254.131 (port 443) after 30000ms: connect failed: ENETUNREACH (Network is unreachable)
</p>
<p>
<strong>Location:</strong>
<br>
io.keen.client.java.KeenClient.handleFailure, line 1345
</p>
<p>
<a href="https://rink.hockeyapp.net/manage/apps/103879/crash_reasons/29510737?no_iphone_ui=true" class="btn btn-success" style="background-color: #389be8;
 background-image: -moz-linear-gradient(top, #4aa4ea, #1c8de5);
 background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#4aa4ea), to(#1c8de5));
 background-image: -webkit-linear-gradient(top, #4aa4ea, #1c8de5);
 background-image: -o-linear-gradient(top, #4aa4ea, #1c8de5);
 background-image: linear-gradient(to bottom, #4aa4ea, #1c8de5);
 background-repeat: repeat-x;
 *background-color: #1c8de5;
 border: 1px solid #cccccc;
 border-bottom-color: #b3b3b3;
 border-color: #1c8de5 #1c8de5 #1363a2;
 border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
 border-radius: 4px;
 -webkit-border-radius: 4px;
 -moz-border-radius: 4px;
 box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
 -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
 -moz-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
 color: #fff;
 display: inline-block;
 filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=&#x27;#ff4aa4ea&#x27;, endColorstr=&#x27;#ff1c8de5&#x27;, GradientType=0);
 filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
 font-size: 13px;
 padding: 4px 10px 4px;
 line-height: 18px;
 margin-bottom: 0;
 text-align: center;
 text-decoration: none;
 text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
 vertical-align: middle;">View on HockeyApp</a>
</p>
</div>
<div class='message-help'>
<p>
If you have any questions, please contact us at
<a href="mailto:support@hockeyapp.net">support@hockeyapp.net</a>
or
<a href="http://support.hockeyapp.net">support.hockeyapp.net</a>.
</p>

</div>
</div>
<div class='below-well'>
<a href="https://rink.hockeyapp.net/manage/notifications">Notification Settings</a>
|
Powered by <a href='http://hockeyapp.com'>HockeyApp</a>
</div>

</div>
</body>
</html>

----==_mimepart_54f60ee2cde1_46fff2e0f4730e3--

**Comment by Geeber** [comment]
Hmm, the KeenClient code shouldn't throw exceptions unless `KeenClient.setDebugMode(true)` has been called. (See https://github.com/keenlabs/KeenClient-Java#logging.) Could you please double-check that you're not calling that somewhere in your app's code?

**Comment by tbarn** [comment]
Closing for now. We can definitely reopen if you want to dig into the issue more.
