### ISSUE TITLE
Keen.location.coordinates becomes invalid on Samsung Galaxy S3

### ISSUE THREAD

**Issue by markdStreetline** [keenlabs/KeenClient-Java#61]
Here is the code I am using to add location coordinates to the Keen Properties.

double[] coordinates = {37.5793,-122.3164}; // new Double[2];
Map<String, Object> keenProperties = new HashMap<String, Object>();
Map<String, Object> keenLocationProperties = new HashMap<String, Object>();
keenLocationProperties.put("coordinates",coordinates );
 keenProperties.put("location", keenLocationProperties);
KeenClient.client().queueEvent("activityEvents", newActivityEvent.toKeenHashMap(sequenceNumber, mPrefs.getString("tag", ""),uuid),keenProperties);

---

When using the above code on Nexus 5, the keen.location.coordinates property looks correct and the data is uploaded to Keen successfully.
However, when running on the Samsung Galaxy S3 the keen.location.coordinates property does not format as an array.  The data does not upload to Keen - I get an error message Invalidpropertyvalueerror in the return JSON from Keen.

See screenshots attached (nexus5.png, samsungS3.png).  
![nexus5](https://cloud.githubusercontent.com/assets/2415123/9312040/2c0d5684-44cf-11e5-901a-3a0833f64edc.png)
![samsungs3](https://cloud.githubusercontent.com/assets/2415123/9312041/2c20e866-44cf-11e5-97d2-5eaebe3321a8.png)

**Comment by Geeber** [comment]
Hi @markdStreetline, thanks for the report. I'm hoping to get some time to work on some SDK issues in the next week or two; is this something that you're urgently blocked on?

Also, can you check the Android version on the Galaxy S3? And, could you try replacing

```java
double[] coordinates = {37.5793,-122.3164}; // new Double[2];
```

with

```java
List<Double> coordinates = java.util.Arrays.asList(37.5793, -122.3164);
```

on the Galaxy S3 and see if that works? (My hypothesis is that for some reason the double[] isn't being handled properly by the serialization logic.)

**Comment by Geeber** [comment]
As an FYI/note to myself (or whoever picks up fixing this): I think the problem is a missing case here: https://github.com/keenlabs/KeenClient-Java/blob/master/android/src/main/java/io/keen/client/android/AndroidJsonHandler.java#L163. We handle `Collection`s but not native Java arrays. This only manifests on older (pre-Android-19) devices, because of the bug described here: https://code.google.com/p/android/issues/detail?id=55114.

**Comment by dkador** [comment]
I have a fix incoming here.
