### ISSUE TITLE
Scoped Key update needed for Java SDK

### ISSUE THREAD

**Issue by mdumanis** [keenlabs/KeenClient-Java#67]
It looks like the Scoped Key structure has changed. The master keys were 32 characters long, but the newer projects have 64 character master keys. This may have been modified in other libraries but does not appear to have been updated in the JS library yet.

This was noticed when a customer began receiving an InvalidKeyException error while attempting to encrypt using the new master API key.

**Comment by dkador** [comment]
I've just release 2.2.0 to Maven (it might take a few minutes to propagate through correctly). Can you please check?
