### ISSUE TITLE
KeenQueryClient NullPointerException 

### ISSUE THREAD

**Issue by tokyohans** [keenlabs/KeenClient-Java#73]
KeenQueryClient throws a NullPointerException if the result == null. The postRequest() method makes an assumption that all queries should return a result. But not all queries without a result are by default "unsuccessful" because it is possible to specify filters that don't generate any matches, so I believe the code block should have an additional check on the existence of error code & message and not throw a KeenQueryClientException unless errorCode and message != null.

```
  // Get the result object.
  Object result = responseMap.get(KeenQueryConstants.RESULT);
  // for successful query, we should get a Result object. But just in case we don't...
  if (result == null) {
    String errorCode = responseMap.get(KeenQueryConstants.ERROR_CODE).toString();
    // ^ this throws a NullPointerException, so perhaps we need if (responseMap.get(...) != null)
    String message = responseMap.get(KeenQueryConstants.MESSAGE).toString();

    String errorMessage = "Error response received from server";
    if (errorCode != null) {errorMessage += " " + errorCode;}
    if (message != null) {errorMessage += ": " + message;}
    throw new KeenQueryClientException(errorMessage);
  }
```

**Comment by dkador** [comment]
I have a fix incoming here.
