### ISSUE TITLE
Add support for Cached Queries

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-Java#87]
## MVP
- [x] Create Saved Query
- [x] Cache a Saved Query
- [x] Uncache a Saved Query
- [x] Delete a Saved Query
- [x] Retrieve Results from Saved Query

## Stretch
- [x] Retrieve definition of a saved query
- [x] Update a cached query

**Comment by masojus** [comment]
Fixed with PR #96 merged in d2e3089
